name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm ci

      - name: Set git user
        run: |
          git config --global user.email "<75044176+RLAlpha49@users.noreply.github.com>"
          git config --global user.name "RLAlpha49"

      - name: Build and Deploy
        run: npm run deploy
        env:
          CI: false